hunter_config(ZLIB
    VERSION ${HUNTER_ZLIB_VERSION}
    CONFIGURATION_TYPES Release
    CMAKE_ARGS
        CMAKE_POSITION_INDEPENDENT_CODE=ON
)

hunter_config(pybind11
    VERSION ${HUNTER_pybind11_VERSION}
    CONFIGURATION_TYPES Release
    CMAKE_ARGS
        CMAKE_POSITION_INDEPENDENT_CODE=ON
)

hunter_config(zstd
    VERSION ${HUNTER_zstd_VERSION}
    CONFIGURATION_TYPES Release
    CMAKE_ARGS
        CMAKE_POLICY_VERSION_MINIMUM=3.10
        CMAKE_POSITION_INDEPENDENT_CODE=ON
)

hunter_config(GTest
    VERSION ${HUNTER_GTest_VERSION}
    CONFIGURATION_TYPES Release
)